name: MAIN Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    uses: kiranvattikuti146/VS-TEST-REUSABLE/.github/workflows/VStest-reusable.yml@main
    with:
      runsOn: "self-hosted"
      dotnet-version: "7.0.x"
      test-assembly: "**/*UnitTests.dll" # Updated pattern to include valid wildcard usage
      code-coverage-enabled: true
      configuration: "Release"
      platform: "x64"
      test-run-title: "Unit Tests"
      run-in-parallel: true
      testPlan: "Plan1"
      testSuite: "SuiteA"
      testConfiguration: "DebugConfig"
      tcmTestRun: "1234"
      uiTests: false
      vsTestVersion: "latest"
      vstestLocation: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\Extensions\\TestPlatform\\vstest.console.exe"
      diagnosticsEnabled: true
      rerunFailedTests: true
      rerunType: "specific"
      rerunMaxAttempts: "3"
      dontDistribute: false
